server.servlet.context-path: /api
spring.datasource.url=jdbc:mysql://localhost:3306/Characters
spring.datasource.username=root
spring.datasource.password=root

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Chave de API para o Google Gemini
google.api.key=AIzaSyBJz6GDNe2UFySurw16_EQVxX5P7pOiPa8
